lsi: false
safe: true
source: /home/adams/xvalad/xvalad.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: Adams Vallejos
affiliation: Göteborgs Universitet
email: adams.vallejos.donoso AT gu.se
google_scholar: https://scholar.google.com//citations?user=FA2XAbgAAAAJ
github_link: https://github.com/xvalad
avatar: https://avatars.githubusercontent.com/u/56148396 